### PR TITLE
Fix some dojo issues for todo-mvc

### PR DESCRIPTION
**Pull request by matt-gadd**
This attempts to fix some of the dojo issues in todo-mvc, i've not got around to the pascal yet but will raise a separate PR if this is acceptable. 

Summary of changes:
* Removed ejected config, now just uses @dojo/cli-build-app
* Removes all superfluous deps
* Uses CSS modules (+ typed css modules)
* Fixes some type errors
* Adds a main.ts and main.css, which replaces the index code and the inlined css in the html
* Uses the tsconfig from cli-create-app template (the recommend config for dojo projects)

### CODE REVIEW

**Comment by vogloblinsky** [comment]
Thanks

**Comment by vogloblinsky** [comment]
@matt-gadd 
- just added missing typescript devDependency
The build seems to run without ending, stays on "... building"
Can you have a look ?

**Comment by vogloblinsky** [comment]
Thanks it works

**Comment by matt-gadd** [comment]
@vogloblinsky thanks a lot again! am i okay to raise the same for the pascal example?

**Comment by vogloblinsky** [comment]
Yes ;)

**Pull request merged**
